name: Srivatsa Demo Workflow

on:
    workflow_dispatch:
jobs:
    srivatsa-demo-job:
        runs-on: ubuntu-latest
        steps:
            - name: Srivatsa Demo step
              run: |
                echo "Hello from Srivatsa Demo!"
                ls -la
                whoami
                echo " Hurray! This is Srivatsa's GitHub Actions demo workflow."
                