name: using jobs in parallel

on: 
    workflow_dispatch
jobs:
    job-01:
        runs-on: ubuntu-latest
        steps:
            - name: Job-01 usage
              run: |
                echo "Job-01 direct usage"
    job-02:
        runs-on: ubuntu-latest
        steps: 
            - name: normal usage of job-02
              run: |
                echo "normal usage of job-02"
    job-03:
        runs-on: ubuntu-latest
        needs: 
            - job-01
            - job-02
        steps:
            - name: usage of job-01 and job-02 before job-03 runs
              run: |
                echo "Hurray! JOB-03 Run using Job-01 and Job-02"
    job-04:
        runs-on: ubuntu-latest
        needs:
            - job-02
            - job-03
        steps:
            - name: usage of job-03 and job-02 before job-04 run
              run: |
                echo "Hurray! Job-04 ran, after usage of job-02 and job-03"




            

    